import assert from 'node:assert/strict';
import {createWorld, CIVIC, ZONE, TERRAIN, civicAnchorOf, civicTiles, jobsOf} from '../js/sim/world.js';
import {apply, costOf, undo} from '../js/sim/ops.js';
import {computeFields, REACH} from '../js/sim/fields.js';
import {lockedReason, computeInfrastructure, medicalLifespanModifier} from '../js/sim/progression.js';
import {createHousehold, placeHousehold} from '../js/sim/citizens.js';
import {save, load, stateHash} from '../js/sim/save.js';
import {tick, refreshLast} from '../js/sim/tick.js';
import {yearlyFigures} from '../js/sim/budget.js';
import {KNOBS} from '../js/sim/rules.js';
const fresh=()=>{const w=createWorld({seed:'health'});w.terrain.fill(TERRAIN.GRASS);w.road.fill(0);w.roadsDirty=true;computeFields(w);return w;};
const grave=fresh(), anchor=20*grave.w+20;
assert.equal(apply(grave,{kind:'cemetery',tx:20,ty:20}).ok,true);
assert.equal(civicTiles(grave,anchor).length,36);
for(const i of civicTiles(grave,anchor))assert.equal(civicAnchorOf(grave,i),anchor,`6×6 ownership ${i}`);
assert.equal(jobsOf(grave,anchor),0);
const h=stateHash(grave);
assert.match(costOf(grave,{kind:'cemetery',tx:40,ty:40}).reason,/one cemetery/i);
assert.equal(apply(grave,{kind:'cemetery',tx:40,ty:40}).ok,false);
assert.equal(stateHash(grave),h);
const copy=load(save(grave));assert.equal(stateHash(copy),h);
for(const i of civicTiles(copy,anchor))assert.equal(civicAnchorOf(copy,i),anchor);
assert.equal(apply(grave,{kind:'bulldoze',x0:25,y0:25,x1:25,y1:25}).ok,true);
assert.equal(grave.civic.some(Boolean),false,'far-corner demolition clears the whole cemetery');
assert.equal(undo(grave).ok,true);assert.equal(civicTiles(grave,anchor).length,36);
const old=fresh();old.civic[anchor]=CIVIC.CEMETERY;old.civicSize[anchor]=2;
for(const [dx,dy] of [[1,0],[0,1],[1,1]]){const i=anchor+dx+dy*old.w;old.civic[i]=CIVIC.PART;old.civicSize[i]=128|dx|dy<<2;}
const oldCopy=load(save(old));assert.equal(civicTiles(oldCopy,anchor+1+old.w).length,4,'legacy cemetery remains intact');
assert.match(costOf(oldCopy,{kind:'cemetery',tx:40,ty:40}).reason,/one cemetery/i);
const campaign=fresh();campaign.flags.campaign={chapter:1,stable:0,entered:0,waste:0,sewage:0};
assert.equal(lockedReason(campaign,{kind:'cemetery'}),'');
assert.match(lockedReason(campaign,{kind:'doctor'}),/Chapter 3/);
campaign.flags.campaign.chapter=2;assert.equal(lockedReason(campaign,{kind:'doctor'}),'');
assert.match(lockedReason(campaign,{kind:'hospital'}),/Chapter 4/);
campaign.flags.campaign.chapter=3;assert.equal(lockedReason(campaign,{kind:'hospital'}),'');
const w=fresh();apply(w,{kind:'road',tiles:Array.from({length:60},(_,y)=>y*w.w+19)});
assert.equal(apply(w,{kind:'hospital',tx:20,ty:20}).ok,true);
const hospital=20*w.w+20;
assert.equal(w.infrastructure.covers.hospital.reduce((a,b)=>a+b),Math.ceil(w.w*w.h*KNOBS.KNOW_UNI_SHARE));
const coverage=[...w.infrastructure.covers.hospital];
w.civic[hospital]=CIVIC.UNIVERSITY;computeFields(w);
assert.deepEqual([...w.civicReach].map(v=>+(!!(v&REACH.UNIVERSITY))),coverage,'hospital uses exactly university coverage');
w.civic[hospital]=CIVIC.HOSPITAL;
assert.equal(apply(w,{kind:'doctor',tx:20,ty:10}).ok,true);
assert.equal(jobsOf(w,hospital),16);assert.equal(jobsOf(w,10*w.w+20),4);
assert.equal(yearlyFigures(w).hospitals,1);assert.equal(yearlyFigures(w).doctors,1);
const home=16*w.w+20;w.zone[home]=ZONE.R;w.tier[home]=1;w.maxTier[home]=1;
const hh=createHousehold(w,'rabbit',1);placeHousehold(w,hh,home);
const c=w.byId.get(hh.members[0]);c.deathAge=1200;c.born=-600;
w.flags.noDisasters=true;
refreshLast(w);assert.equal(w.infrastructure.covers.doctor[home],1);assert.equal(w.infrastructure.covers.hospital[home],1);
assert.equal(medicalLifespanModifier(w,home),0.03,'hospital wins without stacking');
const far=w.w*w.h-1;
assert.equal(medicalLifespanModifier(w,far),0,'distant facility removes penalty outside coverage');
assert.equal(medicalLifespanModifier(w,-1),0,'unhoused citizens avoid penalty with citywide care');
tick(w);assert.equal(c.careBonus,0,'care does not accumulate');
w.flooded[hospital]=1;computeFields(w);
assert.equal(medicalLifespanModifier(w,home),0.02,'doctor remains when hospital floods');
w.flooded[hospital]=0;w.burning[hospital]=1;computeFields(w);
assert.equal(medicalLifespanModifier(w,home),0.02,'burning hospital does not operate');
w.burning[hospital]=0;computeFields(w);
assert.equal(medicalLifespanModifier(w,home),0.03,'repaired service restores bonus');
const medicalCopy=load(save(w));assert.equal(stateHash(medicalCopy),stateHash(w));
tick(w);tick(medicalCopy);assert.equal(stateHash(medicalCopy),stateHash(w),'health continuation is deterministic');
const bad=JSON.parse(save(w));bad.citizens[0].careBonus=-1;assert.throws(()=>load(JSON.stringify(bad)),/Invalid health bonus/);
// A citizen beyond their base lifespan survives under current hospital care.
c.deathAge=600;c.born=w.tick-610;computeInfrastructure(w);tick(w);
assert.equal(c.dead,undefined,'current coverage postpones natural death');
// A legacy credit is accepted but cannot mask the new citywide penalty.
c.born=w.tick-590; // Below base lifespan (600), above the penalized 582 months.
c.careBonus=18;assert.equal(load(save(w)).byId.get(c.id).careBonus,18);
w.road.fill(0);w.roadsDirty=true;computeFields(w);
assert.equal(medicalLifespanModifier(w,home),-0.03,'inactive buildings do not remove penalty');
assert.equal(medicalLifespanModifier(w,-1),-0.03,'penalty also affects unhoused citizens');
assert.equal(medicalLifespanModifier(w,far),-0.03,'penalty applies citywide');
tick(w);assert.ok(c.dead,'aging applies current penalty and ignores legacy credit');
const empty=fresh();empty.flags.campaign={chapter:0,stable:0,entered:0,waste:0,sewage:0};
assert.equal(medicalLifespanModifier(empty,-1),-0.03,'early chapters also lack healthcare');
console.log('Health checks passed: coverage, citywide penalty, closures/restoration, aging, legacy saves, non-stacking, chapter gates, and cemetery checks.');
